### ISSUE TITLE
Set default wifi

### ISSUE THREAD

**Issue by Nollknolle** [pdreker/fritz_exporter#137]
Hey,
is there any way to set the default wifi?
Mine shows "Guest" but is there any way to first choose 5GHz for example?

**Comment by pdreker** [comment]
I assume you mean in the Grafana dashboard?

The values are displayed in whatever order they come from Prometheus, which is more or less random between setups. The reason is, that the WiFi names are extracted from the prometheus data.

If you open the dashboard in Grafa and click on the gear icon in the upper right-hand corner, then go to "Variables" in the menu on the left and choose "wifi", you can see how the variable is setup. At the bottom you can see the preview of values and I would estimate, that this list starts with "Guest" in your case.

You can play with the "Sort" option, maybe one of the settings there produces the right ordering. This is a hack, but it would work.

Alternatively you can reconfigure the variable to Type "Custom" (top right) and simply put the values in the correct order into the "values separated by comma" field. These are just string being replaced in the actual queries which produce the graphs. so `5GHz,2.4GHz,Guest` should do the trick and display the entries in that order and the first one *should* be the default when loading the dashboard.

Don't forget to save the dashboard afterwards.

**Comment by Nollknolle** [comment]
Hey,
jetzt erst gesehen das Du aus Deutschland kommst :D

Tatsächlich kannst Du "Numerisch (desc)" auswählen. Dann zeigt es 5GHz zuerst an. Leider wieso auch immer updatet er es bei mir nicht, obwohl ich gesaved habe. Witzig xD

Danke für deine Antwort und Dir noch eine schöne Woche!
