### ISSUE TITLE
Additional Fritz!Box Fiber metrics

### ISSUE THREAD

**Issue by laugmanuel** [pdreker/fritz_exporter#269]
I'm using a Fritz!Box 5530 Fiber to directly connect to a local fiber network.

The exporter works fine for basic metrics (wifi, wan, lan, ...) but does not contain any fiber specific information.
What's required to add those metrics? I'm willing to provide example data or gather the relevant queries.

**Comment by pdreker** [comment]
This depends, if the box actually exposes those metrics. In the case of tv-cable internet for example the box quite obviously has the information (it is visible in the WebUI), but does not expose them via the API used by the exporter.

You can check out the "data donation" feature which is documented her: https://fritz-exporter.readthedocs.io/en/v2.3.0/helping_out.html

You can check the output yourself, if there is anything, you can find, which is missing from the exporter data and you can upload the data, so I can have a look. **Please read the documentation before actually uploading data!** Due to the nature of the data donation feature I may leak private data to me. The documentation also explains, how to clean that, if needed.

**Comment by laugmanuel** [comment]
Looks like there is not much (if any) fiber specific data in the output.
However, I've uploaded a sanitized version anyway - maybe you can find more information.

The data is linked to fb0db37c-498a-459b-b556-f08aefadd691

**Comment by pdreker** [comment]
I had a look and I also cannot find any *fiber specific* information. Fiber is a bit special, when compared to DSL or cable, as there is way less signal processing and trickery going on. It just "Yes, there is light" or "No, there isn't". From my experience with bigger fiber optics systems, even there the best most devices have is the transmit and receive power values and verry rarely anything beyond those.

I'll close this, for now. I should get my own fiber internet some time next year, which will then probably prompt me to revisit this, if I can extract something :-)

**Comment by laugmanuel** [comment]
Just to complete this, the Fritz!Box shows the following information on the web interface:

- SFP specific information
  - internal temperature in °C
  - internal voltage in V
  - sending current in mA
  - sending power in dBm
  - receiving power in dBm
  - wavelength send in nm
  - wavelength receive in nm
  - connector type

- connection specific information
  - ranging time
  - omci packets
  - multicast packets
  - unicast packets

And a few more non-interesting information like serial number, encryption state, sfp module name...
