### ISSUE TITLE
Secure credentials for multi device environments

### ISSUE THREAD

**Issue by ngc4579** [pdreker/fritz_exporter#59]
Configuring fritz_exporter by passing environment variables included passing credentials through "hidden" _.env_ files. This seems no longer possible when using a configuration file.

**Comment by pdreker** [comment]
There should not be a technical difference between using the config file and the .env file, just because the .env file is not shown by `ls` by default (There is nothing special about hidden files, other than their name starting with a '.'.

The fact that `.env` worked before was more of a coincidence and not an intended feature. ;-)

The backstory is that the 1.x Docker images used `/bin/sh` as the Entrypoint and ran the exporter from the `Command` attribute of the Dockerfile. The 2.x image runs the exporter from the entrypoint, thus doing away with the shell, which read the `.env` file.

What is the specific use case, that cannot be solved by using the config file? Maybe I'm just not seeing the problem.

**Comment by ngc4579** [comment]
Thanks for the background explanation.

I've set up a private GitLab Repository holding a _docker-compose.yml_. With fritz_exporter 1.x, I had configured credentials using the `FRITZ_EXPORTER_CONFIG` environment variable:

```
environment:
            - "FRITZ_EXPORTER_CONFIG=192.168.x.x,${USR},${PW},192.168.x.x,${USR},${PW}"
```

In Addition, the `$USR` and `$PW` variables used above were configured in an additional env file that was **not** committed to the repository.

Using a config file, I see no trivial means to store credentials outside that config ATM, and although the utilized repository is a private one, I actually do not intend to store any such sensitive credentials there.

**Comment by pdreker** [comment]
How do you get the .env file into the container? Do you build your own image on top of the published one?

**Comment by ngc4579** [comment]
The .env file does not go into the container - that's rather a Docker Compose [feature](https://docs.docker.com/compose/environment-variables/#the-env-file). Apart from that, I'm using the default image from Docker Hub.

**Comment by pdreker** [comment]
OK, after a bit of reading and more thinking about it, I find, that my explanation above missed the point...

Basically you are using a multi device config via environment config (FRITZ_EXPORTER_CONFIG) and use the .env mechanism of docker-compose to create a valid config when deploying.

Basically (maybe wrong in details, but the basic idea should be right):
* docker-compose.yml in GitLab, with the environment line as quoted above (https://github.com/pdreker/fritz_exporter/issues/59#issuecomment-830856225)
* when you deploy (locally probably) you run `docker-compose up -d` and locally an `.env` file provides user/pw data, which is substituted by docker-compose and the deployment is brought up.

Right?

So you have a local "secret" file (`.env`) + the docker-compose.yml from git and due to the environment config in 2.x not supporting multiple devices you would have to use the config file, which in turn does not work, because you cannot modify that config file by using docker-compose's `.env` mechanism...

Why not treat the whole config file as "secret"? So create a `fritz-exporter.yml` to mount into the container and use the `--config` option of the exporter, but do not commit the `fritz-exporter.yml` to git? Not quite as reduced as the prior approach, but works. The config file is not that complex, that you *must* have it in git.

If you want things separated using `envsubst` would be an option. Basically create a `fritz-exporter-git.yml` like this (and commit it to git):
```yaml
devices:
  - name: Fritz!Box 7590 Router
    hostname: fritz.box
    username: ${USR}
    password: ${PW}
  - name: Repeater01
    hostname: repeater-01
    username: ${USR}
    password: ${PW}
```
To generate the production config you can then do `USR=myuser PW=geheim1234 envsubst < fritz-exporter-git.yml > fritz-exporter-prod.yml` and then mount the latter into the container.

Another option I use professionally is to encrypt secrets in git using GnuPG and/or SOPS, but then again my kubernetes clusters will automatically decrypt these as needed, so in a docker-compose setup this may by a step too far.

Is that a viable solution for your use-case?

**Comment by pdreker** [comment]
Ah and another option: you could run two exporters - one for each device. In that way you can again use the environment configuration, which in turn makes the `.env` approach feasible again.

**Comment by ngc4579** [comment]
Yes, the latter would actually be an option - I think for the time being I'd go with that one. Another option would possibly be using Docker's secrets system, but that would also require changes to how configuration works. Anyway - thanks for the hint.

**Comment by pdreker** [comment]
I will keep this issue open for now, as a reminder for me, to think about the problem and how to solve that elegantly.

**Comment by pdreker** [comment]
Storing secrets and Git Repos are an ever delightful problem in DevOps especially. All solutions for this type of problem are external to the application in question (Hashicorp Vault, SOPS, gitcrypt, ...)

As a workaround for that specific use case exists and I cannot come up with an elegant solution without making config parsing in the exporter needlessly complex, I will close this issue.
