### ISSUE TITLE
Any way to monitor remote fritz!boxes via MyFritz?

### ISSUE THREAD

**Issue by antifuchs** [pdreker/fritz_exporter#71]
I am trying to keep tabs on the internet connections to three remote sites, and have set up their fritz!boxes to be reachable remotely via MyFritz (https://www.myfritz.net/devices/); it looks like the webface that is exposed via this doesn't export the igddesc.xml file, though:

```console
$ curl 'https://me:password@a-very-long-random-string.myfritz.net:44369/igddesc.xml'
*   Trying 2a01:aea0:df4:1::5c29:44369...
* Connected to a-very-long-random-string.myfritz.net (2a01:aea0:df4:1::5c29) port 44369 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=a-very-long-random-string.myfritz.net
*  start date: Jun 18 12:03:05 2022 GMT
*  expire date: Sep 16 12:03:04 2022 GMT
*  subjectAltName: host "a-very-long-random-string.myfritz.net" matched cert's "a-very-long-random-string.myfritz.net"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Server auth using Basic with user 'me'
> GET /igddesc.xml HTTP/1.1
> Host: a-very-long-random-string.myfritz.net:44369
> Authorization: Basic ========
> User-Agent: curl/7.83.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Connection: close
< Content-Length: 1705
< Content-Type: text/html; charset=utf-8
<
...
```

Is there any hope that the exporter could work with a remote fritz!box? I would hate to have to drop little computers that run the exporter in the local network (especially in the current supply chain situation)...

**Comment by pdreker** [comment]
Remote is going to be near imposiible ("near" because I'm not 100% sure), but TR-064 is normally not used for external access, so the box itself will not expose the necessary interface on the outside.

There are several options that com to mind:
1. for generic "connectivity checks" use a blackbox exporter instance (https://github.com/prometheus/blackbox_exporter), to check if the myfritz page returns the expected data. Might need some experimentation but *could* be an option. This will not deliver any Fritz! specific information but should be able to telle, if the site is up or down by matching a regular expression in the returned page for example.
2. run an instance of fritz-exporter "behind" the remote fritzbox and expose it via a port-forward. Then scrape it via static configuration from your prometheus instance. NOTE: this will expose the monitoring data to the internet without any access control! Some form of authentication should be used in this case.
3. Setup a VPN Tunnel between the sites and check the functionality of the tunnel, e.g. via blackbox-exporter "ping". This also enables to scrape a remote instance of fritz-exporter across the VPN without exposing the monitoring data unauthenticated to the internet.

So the reason for not doing "remote" is inherent in the mechanism used in the exporter (TR-064). The exporter can run on almost any kind oft hardware (also: without docker if needed), so any old Raspi would potentially do the job. Also Snyology/QNAP NASes will run Docker containers and as such can run the exporter.

If you just want to know, if the remote is connected or not: Simply use blackbox-exporter to connect to the remote WebInterface and check if it returns the expected response.

**Comment by pdreker** [comment]
I just checked the docs:
Actually newer fritzbox versions should be doing TR-064 remotely just fine.

You will have to connect to the fritz-box directly using a DynDNS Hostname instead of going through the MyFritz Redirect.

Please see: https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AVM_TR-064_remote.pdf

According to this it will "just work" when certain prerequisites (Username/Password,m remote access enabled etc.) are fulfilled.
